/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as DesignRouteImport } from './routes/design'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPasswordRouteImport } from './routes/admin/password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as CalendarEventIdRouteImport } from './routes/calendar/$eventId'
import { Route as CalendarNewRouteImport } from './routes/calendar/new'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalEntryIdRouteImport } from './routes/journal/$entryId'
import { Route as JournalDraftsRouteImport } from './routes/journal/drafts'
import { Route as JournalNewRouteImport } from './routes/journal/new'
import { Route as JournalTrashRouteImport } from './routes/journal/trash'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as MembersInviteRouteImport } from './routes/members/invite'
import { Route as WishlistIndexRouteImport } from './routes/wishlist/index'
import { Route as WishlistMemberIdRouteImport } from './routes/wishlist/$memberId'
import { Route as WishlistFavoritesRouteImport } from './routes/wishlist/favorites'
import { Route as WishlistMineRouteImport } from './routes/wishlist/mine'
import { Route as AdminSpacesSpaceIdRouteImport } from './routes/admin/spaces/$spaceId'
import { Route as CalendarEventIdEditRouteImport } from './routes/calendar/$eventId_.edit'
import { Route as JournalEntryIdEditRouteImport } from './routes/journal/$entryId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPasswordRoute = AdminPasswordRouteImport.update({
  id: '/admin/password',
  path: '/admin/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarEventIdRoute = CalendarEventIdRouteImport.update({
  id: '/calendar/$eventId',
  path: '/calendar/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarNewRoute = CalendarNewRouteImport.update({
  id: '/calendar/new',
  path: '/calendar/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntryIdRoute = JournalEntryIdRouteImport.update({
  id: '/journal/$entryId',
  path: '/journal/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDraftsRoute = JournalDraftsRouteImport.update({
  id: '/journal/drafts',
  path: '/journal/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalTrashRoute = JournalTrashRouteImport.update({
  id: '/journal/trash',
  path: '/journal/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersInviteRoute = MembersInviteRouteImport.update({
  id: '/members/invite',
  path: '/members/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistIndexRoute = WishlistIndexRouteImport.update({
  id: '/wishlist/',
  path: '/wishlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistMemberIdRoute = WishlistMemberIdRouteImport.update({
  id: '/wishlist/$memberId',
  path: '/wishlist/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistFavoritesRoute = WishlistFavoritesRouteImport.update({
  id: '/wishlist/favorites',
  path: '/wishlist/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistMineRoute = WishlistMineRouteImport.update({
  id: '/wishlist/mine',
  path: '/wishlist/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpacesSpaceIdRoute = AdminSpacesSpaceIdRouteImport.update({
  id: '/admin/spaces/$spaceId',
  path: '/admin/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarEventIdEditRoute = CalendarEventIdEditRouteImport.update({
  id: '/calendar/$eventId_/edit',
  path: '/calendar/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntryIdEditRoute = JournalEntryIdEditRouteImport.update({
  id: '/journal/$entryId_/edit',
  path: '/journal/$entryId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/calendar/new': typeof CalendarNewRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/drafts': typeof JournalDraftsRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/trash': typeof JournalTrashRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/invite': typeof MembersInviteRoute
  '/wishlist/$memberId': typeof WishlistMemberIdRoute
  '/wishlist/favorites': typeof WishlistFavoritesRoute
  '/wishlist/mine': typeof WishlistMineRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/members/': typeof MembersIndexRoute
  '/wishlist/': typeof WishlistIndexRoute
  '/admin/spaces/$spaceId': typeof AdminSpacesSpaceIdRoute
  '/calendar/$eventId/edit': typeof CalendarEventIdEditRoute
  '/journal/$entryId/edit': typeof JournalEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/calendar/new': typeof CalendarNewRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/drafts': typeof JournalDraftsRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/trash': typeof JournalTrashRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/invite': typeof MembersInviteRoute
  '/wishlist/$memberId': typeof WishlistMemberIdRoute
  '/wishlist/favorites': typeof WishlistFavoritesRoute
  '/wishlist/mine': typeof WishlistMineRoute
  '/admin': typeof AdminIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/journal': typeof JournalIndexRoute
  '/members': typeof MembersIndexRoute
  '/wishlist': typeof WishlistIndexRoute
  '/admin/spaces/$spaceId': typeof AdminSpacesSpaceIdRoute
  '/calendar/$eventId/edit': typeof CalendarEventIdEditRoute
  '/journal/$entryId/edit': typeof JournalEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/calendar/new': typeof CalendarNewRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/drafts': typeof JournalDraftsRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/trash': typeof JournalTrashRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/invite': typeof MembersInviteRoute
  '/wishlist/$memberId': typeof WishlistMemberIdRoute
  '/wishlist/favorites': typeof WishlistFavoritesRoute
  '/wishlist/mine': typeof WishlistMineRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/members/': typeof MembersIndexRoute
  '/wishlist/': typeof WishlistIndexRoute
  '/admin/spaces/$spaceId': typeof AdminSpacesSpaceIdRoute
  '/calendar/$eventId_/edit': typeof CalendarEventIdEditRoute
  '/journal/$entryId_/edit': typeof JournalEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/design'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/signin'
    | '/admin/login'
    | '/admin/password'
    | '/admin/settings'
    | '/calendar/$eventId'
    | '/calendar/new'
    | '/journal/$entryId'
    | '/journal/drafts'
    | '/journal/new'
    | '/journal/trash'
    | '/members/$memberId'
    | '/members/invite'
    | '/wishlist/$memberId'
    | '/wishlist/favorites'
    | '/wishlist/mine'
    | '/admin/'
    | '/calendar/'
    | '/journal/'
    | '/members/'
    | '/wishlist/'
    | '/admin/spaces/$spaceId'
    | '/calendar/$eventId/edit'
    | '/journal/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/design'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/signin'
    | '/admin/login'
    | '/admin/password'
    | '/admin/settings'
    | '/calendar/$eventId'
    | '/calendar/new'
    | '/journal/$entryId'
    | '/journal/drafts'
    | '/journal/new'
    | '/journal/trash'
    | '/members/$memberId'
    | '/members/invite'
    | '/wishlist/$memberId'
    | '/wishlist/favorites'
    | '/wishlist/mine'
    | '/admin'
    | '/calendar'
    | '/journal'
    | '/members'
    | '/wishlist'
    | '/admin/spaces/$spaceId'
    | '/calendar/$eventId/edit'
    | '/journal/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/design'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/signin'
    | '/admin/login'
    | '/admin/password'
    | '/admin/settings'
    | '/calendar/$eventId'
    | '/calendar/new'
    | '/journal/$entryId'
    | '/journal/drafts'
    | '/journal/new'
    | '/journal/trash'
    | '/members/$memberId'
    | '/members/invite'
    | '/wishlist/$memberId'
    | '/wishlist/favorites'
    | '/wishlist/mine'
    | '/admin/'
    | '/calendar/'
    | '/journal/'
    | '/members/'
    | '/wishlist/'
    | '/admin/spaces/$spaceId'
    | '/calendar/$eventId_/edit'
    | '/journal/$entryId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DesignRoute: typeof DesignRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPasswordRoute: typeof AdminPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CalendarEventIdRoute: typeof CalendarEventIdRoute
  CalendarNewRoute: typeof CalendarNewRoute
  JournalEntryIdRoute: typeof JournalEntryIdRoute
  JournalDraftsRoute: typeof JournalDraftsRoute
  JournalNewRoute: typeof JournalNewRoute
  JournalTrashRoute: typeof JournalTrashRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersInviteRoute: typeof MembersInviteRoute
  WishlistMemberIdRoute: typeof WishlistMemberIdRoute
  WishlistFavoritesRoute: typeof WishlistFavoritesRoute
  WishlistMineRoute: typeof WishlistMineRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  WishlistIndexRoute: typeof WishlistIndexRoute
  AdminSpacesSpaceIdRoute: typeof AdminSpacesSpaceIdRoute
  CalendarEventIdEditRoute: typeof CalendarEventIdEditRoute
  JournalEntryIdEditRoute: typeof JournalEntryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/password': {
      id: '/admin/password'
      path: '/admin/password'
      fullPath: '/admin/password'
      preLoaderRoute: typeof AdminPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$eventId': {
      id: '/calendar/$eventId'
      path: '/calendar/$eventId'
      fullPath: '/calendar/$eventId'
      preLoaderRoute: typeof CalendarEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/new': {
      id: '/calendar/new'
      path: '/calendar/new'
      fullPath: '/calendar/new'
      preLoaderRoute: typeof CalendarNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$entryId': {
      id: '/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/journal/$entryId'
      preLoaderRoute: typeof JournalEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/drafts': {
      id: '/journal/drafts'
      path: '/journal/drafts'
      fullPath: '/journal/drafts'
      preLoaderRoute: typeof JournalDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/trash': {
      id: '/journal/trash'
      path: '/journal/trash'
      fullPath: '/journal/trash'
      preLoaderRoute: typeof JournalTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/invite': {
      id: '/members/invite'
      path: '/members/invite'
      fullPath: '/members/invite'
      preLoaderRoute: typeof MembersInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/': {
      id: '/wishlist/'
      path: '/wishlist'
      fullPath: '/wishlist/'
      preLoaderRoute: typeof WishlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/$memberId': {
      id: '/wishlist/$memberId'
      path: '/wishlist/$memberId'
      fullPath: '/wishlist/$memberId'
      preLoaderRoute: typeof WishlistMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/favorites': {
      id: '/wishlist/favorites'
      path: '/wishlist/favorites'
      fullPath: '/wishlist/favorites'
      preLoaderRoute: typeof WishlistFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/mine': {
      id: '/wishlist/mine'
      path: '/wishlist/mine'
      fullPath: '/wishlist/mine'
      preLoaderRoute: typeof WishlistMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spaces/$spaceId': {
      id: '/admin/spaces/$spaceId'
      path: '/admin/spaces/$spaceId'
      fullPath: '/admin/spaces/$spaceId'
      preLoaderRoute: typeof AdminSpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$eventId_/edit': {
      id: '/calendar/$eventId_/edit'
      path: '/calendar/$eventId/edit'
      fullPath: '/calendar/$eventId/edit'
      preLoaderRoute: typeof CalendarEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$entryId_/edit': {
      id: '/journal/$entryId_/edit'
      path: '/journal/$entryId/edit'
      fullPath: '/journal/$entryId/edit'
      preLoaderRoute: typeof JournalEntryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DesignRoute: DesignRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPasswordRoute: AdminPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CalendarEventIdRoute: CalendarEventIdRoute,
  CalendarNewRoute: CalendarNewRoute,
  JournalEntryIdRoute: JournalEntryIdRoute,
  JournalDraftsRoute: JournalDraftsRoute,
  JournalNewRoute: JournalNewRoute,
  JournalTrashRoute: JournalTrashRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersInviteRoute: MembersInviteRoute,
  WishlistMemberIdRoute: WishlistMemberIdRoute,
  WishlistFavoritesRoute: WishlistFavoritesRoute,
  WishlistMineRoute: WishlistMineRoute,
  AdminIndexRoute: AdminIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  WishlistIndexRoute: WishlistIndexRoute,
  AdminSpacesSpaceIdRoute: AdminSpacesSpaceIdRoute,
  CalendarEventIdEditRoute: CalendarEventIdEditRoute,
  JournalEntryIdEditRoute: JournalEntryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
