/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPasswordRouteImport } from './routes/admin/password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSpacesSpaceIdRouteImport } from './routes/admin/spaces/$spaceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPasswordRoute = AdminPasswordRouteImport.update({
  id: '/admin/password',
  path: '/admin/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpacesSpaceIdRoute = AdminSpacesSpaceIdRouteImport.update({
  id: '/admin/spaces/$spaceId',
  path: '/admin/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/spaces/$spaceId': typeof AdminSpacesSpaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/spaces/$spaceId': typeof AdminSpacesSpaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/spaces/$spaceId': typeof AdminSpacesSpaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/admin/login'
    | '/admin/password'
    | '/admin/settings'
    | '/admin/'
    | '/admin/spaces/$spaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/admin/login'
    | '/admin/password'
    | '/admin/settings'
    | '/admin'
    | '/admin/spaces/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/admin/login'
    | '/admin/password'
    | '/admin/settings'
    | '/admin/'
    | '/admin/spaces/$spaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPasswordRoute: typeof AdminPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSpacesSpaceIdRoute: typeof AdminSpacesSpaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/password': {
      id: '/admin/password'
      path: '/admin/password'
      fullPath: '/admin/password'
      preLoaderRoute: typeof AdminPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spaces/$spaceId': {
      id: '/admin/spaces/$spaceId'
      path: '/admin/spaces/$spaceId'
      fullPath: '/admin/spaces/$spaceId'
      preLoaderRoute: typeof AdminSpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPasswordRoute: AdminPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSpacesSpaceIdRoute: AdminSpacesSpaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
