import { and, asc, eq, inArray } from 'drizzle-orm'
import type { Executor, Tx } from '../../platform/db/index.ts'
import { type EntryImage, entryImages, type imageStates } from './tables.ts'

type ImageState = (typeof imageStates)[number]

export interface NewEntryImage {
  /** Generated by the service before the upload: the object key names it. */
  id: string
  entryId: string
  uploaderMemberId: string
  originalBytes: number
  originalSha256: string
  originalContentType: string
  revision: bigint
  now: Date
}

/**
 * Every query on this space-owned table takes the space as its required
 * first argument (architecture.md, "Space scoping"); the photo's own id
 * never reaches a row outside its space.
 */
export async function insertImage(
  tx: Tx,
  spaceId: string,
  data: NewEntryImage,
): Promise<EntryImage> {
  const inserted = await tx
    .insert(entryImages)
    .values({
      id: data.id,
      spaceId,
      entryId: data.entryId,
      uploaderMemberId: data.uploaderMemberId,
      originalBytes: data.originalBytes,
      originalSha256: data.originalSha256,
      originalContentType: data.originalContentType,
      state: 'processing',
      revision: data.revision,
      createdAt: data.now,
      updatedAt: data.now,
    })
    .returning()
  const row = inserted[0]
  if (!row) throw new Error('Inserting an entry image returned no row')
  return row
}

export async function getImageInSpace(
  executor: Executor,
  spaceId: string,
  imageId: string,
): Promise<EntryImage | undefined> {
  const rows = await executor
    .select()
    .from(entryImages)
    .where(and(eq(entryImages.spaceId, spaceId), eq(entryImages.id, imageId)))
    .limit(1)
  return rows[0]
}

/**
 * The photos of several entries, oldest first within an entry — one query
 * for a feed page, a drafts list, or a sync delta. Ordered by (entryId,
 * createdAt) so the caller can group them in memory.
 */
export async function listImagesForEntries(
  executor: Executor,
  spaceId: string,
  entryIds: readonly string[],
): Promise<EntryImage[]> {
  if (entryIds.length === 0) return []
  return executor
    .select()
    .from(entryImages)
    .where(and(eq(entryImages.spaceId, spaceId), inArray(entryImages.entryId, [...entryIds])))
    .orderBy(asc(entryImages.entryId), asc(entryImages.createdAt), asc(entryImages.id))
}

/** How many photos an entry already carries — the per-entry cap's count. */
export async function countImagesOfEntry(
  executor: Executor,
  spaceId: string,
  entryId: string,
): Promise<number> {
  const rows = await executor
    .select({ id: entryImages.id })
    .from(entryImages)
    .where(and(eq(entryImages.spaceId, spaceId), eq(entryImages.entryId, entryId)))
  return rows.length
}

/**
 * The worker's write: the derivatives exist (or the photo finally failed),
 * stamped with the transaction's revision so the entry — whose DTO embeds
 * the photo — travels to every device again.
 */
export async function updateImageState(
  tx: Tx,
  spaceId: string,
  imageId: string,
  changes: { state: ImageState; width?: number; height?: number },
  revision: bigint,
  now: Date,
): Promise<EntryImage | undefined> {
  const updated = await tx
    .update(entryImages)
    .set({
      state: changes.state,
      width: changes.width ?? null,
      height: changes.height ?? null,
      revision,
      updatedAt: now,
    })
    .where(and(eq(entryImages.spaceId, spaceId), eq(entryImages.id, imageId)))
    .returning()
  return updated[0]
}

/**
 * The author's removal of one photo (issue #17). The delete is guarded by
 * the entry it belongs to; a photo of another entry — or another space —
 * returns no row, and the use case refuses.
 */
export async function deleteImage(
  tx: Tx,
  spaceId: string,
  entryId: string,
  imageId: string,
): Promise<EntryImage | undefined> {
  const deleted = await tx
    .delete(entryImages)
    .where(
      and(
        eq(entryImages.spaceId, spaceId),
        eq(entryImages.entryId, entryId),
        eq(entryImages.id, imageId),
      ),
    )
    .returning()
  return deleted[0]
}
